#!/bin/bash
echo "Setting permissions...":
if [ ${USER_ID:-999} -ne 999 ] && [ ${GROUP_ID:-999} -ne 999 ]; then 
    echo "Setting permissions... for User $USER_ID and Group $GROUP_ID"
    mkdir -p $HOME
    mkdir -p /var/cache/app
	usermod -d $HOME \
            --shell /bin/bash \
            -u $USER_ID \
            www-data
    groupmod -g $GROUP_ID www-data

    chown -R www-data:www-data \
        /home/www-data \
        /var/cache/app \
        /var/lib/php/sessions/ \
        $APP_DIR
fi