#!/bin/bash

echo "[STARTUP] Starting the container"

echo "[STARTUP] - Creating /tmp/CONTAINER_STARTING"
touch /tmp/CONTAINER_STARTING
if [ -f "/tmp/CONTAINER_STARTED" ]; then
    echo "[STARTUP] - Removing previously started indicator at /tmp/CONTAINER_STARTED"
    rm /tmp/CONTAINER_STARTED
fi 