#!/bin/bash

# Environment
echo "[STARTUP] Environment File $FILE_PARAMETERS..."
if [ -f $FILE_PARAMETERS ]; then
    rm $FILE_PARAMETERS
fi

sudo -u www-data cp $FILE_PARAMETERS_DIST $FILE_PARAMETERS
args=() i=0
for var in $(compgen -e); do
    VALUE=`echo ${!var} | sed -r 's/\./\\\\./g'`
    sudo -u www-data sed -i "s.\$${var}.${VALUE}.g" $FILE_PARAMETERS  > /dev/null
done