#!/bin/bash

# Environment
echo "[STARTUP] Environment File $FILE_PARAMETERS..."
if [ -f $FILE_PARAMETERS ]; then
    rm $FILE_PARAMETERS
fi

sudo -u www-data cp $FILE_PARAMETERS_DIST $FILE_PARAMETERS
args=() i=0
for var in $(compgen -e); do
    VALUE=`echo ${!var} | sed -r 's/\./\\\\./g'`
    sudo -u www-data sed -i "s.\$${var}.${VALUE}.g" $FILE_PARAMETERS  > /dev/null
done

## Composer
echo "[STARTUP] Composer build..."
if [ "$SF_APP_ENV" == "dev" ]; then
    sudo -u www-data composer install -d $APP_ROOT
else
    sudo -u www-data composer install --no-dev -o -d $APP_ROOT
fi

# Yarn
echo "[STARTUP] Yarn build..."
sudo -u www-data yarn --cwd $APP_ROOT install --non-interactive
if [ "$SF_APP_ENV" == "dev" ]; then
    sudo -u www-data yarn --cwd $APP_ROOT encore dev --non-interactive
else
    sudo -u www-data yarn --cwd $APP_ROOT encore production --non-interactive
fi

# Cache
echo "[STARTUP] Clearing cache..."
sudo -u www-data $APP_ROOT/bin/console cache:clear --no-warmup
sudo -u www-data $APP_ROOT/bin/console cache:warmup