#!/bin/bash

# Environment
echo "[STARTUP] Environment File $FILE_PARAMETERS..."
if [ -f $FILE_PARAMETERS ]; then
    rm $FILE_PARAMETERS
fi

cp $FILE_PARAMETERS_DIST $FILE_PARAMETERS
args=() i=0
for var in $(compgen -e); do
    VALUE=`echo ${!var} | sed -r 's/\./\\\\./g'`
    sed -i "s.\$${var}.${VALUE}.g" $FILE_PARAMETERS  > /dev/null
done

## Composer
echo "[STARTUP] Composer build..."
if [ "$SF_APP_ENV" == "dev" ]; then
    composer install -d $APP_ROOT
elif [ "$SF_APP_ENV" == "prod" ]; then
    composer install --no-dev -o -d $APP_ROOT
fi

# Yarn
echo "[STARTUP] Yarn build..."
yarn --cwd $APP_ROOT install --non-interactive
if [ "$SF_APP_ENV" == "dev" ]; then
    yarn --cwd $APP_ROOT encore dev --non-interactive
elif [ "$SF_APP_ENV" == "prod" ]; then
    yarn --cwd $APP_ROOT encore production --non-interactive
fi

# Cache
echo "[STARTUP] Clearing cache..."
$APP_ROOT/bin/console cache:clear --no-warmup
$APP_ROOT/bin/console cache:warmup