#!/bin/bash

# Cache
echo "[STARTUP] Clearing cache..."
sudo -u www-data $SYMFONY_CONSOLE cache:clear --no-warmup >> /dev/null
echo "[STARTUP] Warming up cache..."
sudo -u www-data $SYMFONY_CONSOLE cache:warmup >> /dev/null