#!/bin/bash

if [ "$FXPHP_BUILD" = "1" ]; then return; fi


echo "Waiting for MySQL Server..."
while ! mysqladmin ping -h"$MYSQL_HOST" --silent; do
	echo "Waiting for MySQL Server..."
    sleep 3
done
echo "MySQL is up!"