#!/bin/bash

if [ "$FXPHP_BUILD" = "1" ]; then exit; fi


echo "[STARTUP] Waiting for MySQL Server..."
while ! mysqladmin ping -h"$MYSQL_HOST" --silent; do
	echo "[STARTUP] - Still waiting for MySQL Server..."
    sleep 3
done
echo "[STARTUP] - MySQL is up!"