#!/bin/bash

echo "[STARTUP] Migrating the database..."
if [ "$FXPHP_BUILD" = "1" ]; then 
    echo "[STARTUP] - Not migrating, FXPHP_BUILD = 1 (Builds dont have a database)"
fi

echo "[STARTUP] - Running..."
sudo -u www-data $APP_ROOT/bin/console doctrine:migrations:migrate --no-interaction >> /dev/null