defaultbuild: &defaultbuild
  stage: build
  tags:
    - docker-host
defaultdeploy: &defaultdeploy
  stage: deploy
  tags:
    - docker-host

build-7.3:
  <<: *defaultbuild
  script:
    - ./build.sh 7.3 build

build-7.4:
  <<: *defaultbuild
  script:
    - ./build.sh 7.4 build

build-8.0:
  <<: *defaultbuild
  script:
    - ./build.sh 8.0 build

deploy-7.3:
  <<: *defaultdeploy
  script:
    - ./build.sh 7.3 push
  needs:
    - job: build-7.3

deploy-7.4:
  <<: *defaultdeploy
  script:
    - ./build.sh 7.4 push
  needs:
    - job: build-7.4

deploy-8.0:
  <<: *defaultdeploy
  script:
    - ./build.sh 8.0 push
  needs:
    - job: build-8.0


