name: 'Build the docker images'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/build.sh 7.3 build
      shell: bash
    - run: ${{ github.action_path }}/build.sh 7.4 build
      shell: bash
    - run: ${{ github.action_path }}/build.sh 8.0 build
      shell: bash