# Use root/example as user/password credentials
version: "3"

services:
  db:
    image: mariadb
    env_file: .env
    ports:
      - 127.0.0.1:9802:3306
    volumes:
      - /var/lib/mysql
  app:
    depends_on:
      - db
    image: fluxter/web-php:7.4-dev
    env_file: .env
    environment:
      ENV: dev
    ports:
      - 9800:8080
      - 9803:8443
    volumes:
      - ..:/workspace:cached
      - ../src/:/var/www/html

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - 9801:80
    environment:
      - PMA_HOST=db
      - UPLOAD_LIMIT=2G
